language: cpp
dist: bionic
matrix:
  include:
    - #dist: bionic
      compiler: gcc
      os: linux
      sudo: required
addons:
  apt:
    packages:
      - qtbase5-dev
      - libtelepathy-qt5-dev
      - libphonenumber-dev
      - dbus-test-runner
      - dconf-cli
      - gnome-keyring
      - libmission-control-plugins-dev
      - libqt5sql5-sqlite
      - libsqlite3-dev
      - qt5-default
      - sqlite3
      - telepathy-mission-control-5
      - doxygen
      - libqofono-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install -y qtbase5-dev libtelepathy-qt5-dev libphonenumber-dev dbus-test-runner dconf-cli gnome-keyring libmission-control-plugins-dev libqt5sql5-sqlite libsqlite3-dev qt5-default sqlite3 telepathy-mission-control-5 doxygen libqofono-dev

script:
 - mkdir build && cd build
 - cmake ../
 - make -j4
 - make test
 - ctest --output-on-failure
